name: test
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  solid_lints: ^0.0.14

dependencies:
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
